### ISSUE TITLE
Undo manager?

### ISSUE THREAD

**Issue by adib** [karelia/BSManagedDocument#16]
I wonder why there's no override to `undoManager` that returns the main object context's undo manager? Is it deliberate?

**Comment by mikeabdullah** [comment]
Yes, it's deliberate. The document's undo manager is set to be that of the context, so `-undoManager` returns the right thing.

We could conceivably achieve the same effect by overriding `-undoManager`, but the major issue there is it breaks `NSDocument`'s integration with the undo manager. (i.e. it doesn't notice when changes occur).

Is there something about the current implementation that's bothering you?

**Comment by adib** [comment]
I  remember vaguely in 10.5 I had to override undoManager to return the object context's undo manager on certain cases. But if you're sure that NSDocument already knows how to get the MOC's undo manager, then probably it's not necessary.

**Comment by mikeabdullah** [comment]
I've not seen any ill-effects from the current implementation so far, and have been shipping with that technique for several years now. There may be something I've missed though.

The one downside of this approach is that a client could make the mistake of changing the MOC's undo manager for a different instance. If this were to happen, the document wouldn't notice the change. But I figure the risk of this is outweighed by having document change tracking actually work!
