### ISSUE TITLE
Validation errors are neglected during save operation

### ISSUE THREAD

**Issue by sebromero** [karelia/BSManagedDocument#18]
Inside the method -saveToURL:ofType:forSaveOperation:completionHandler: there is a call to contentsForURL:ofType:saveOperation:error: which on 10.7+ saves the parent context. This may fail due to validation errors for example.

```
_contents = [self contentsForURL:url ofType:typeName saveOperation:saveOperation error:&error];
```

Because this method always returns a block object, the following if statement is never executed:

```
    if (!_contents){
        NSAssert(error, @"-additionalContentForURL:ofType:forSaveOperation:error: failed with a nil error");
        fileAccessCompletionHandler();
        if (completionHandler) completionHandler(error);
        return;
    }
```

Therefore saving errors may go unnoticed.

**Comment by mikeabdullah** [comment]
Thanks for spotting this Sebastian. Can you confirm it's now fixed and close this issue, please?

**Comment by sebromero** [comment]
Thanks for the quick fix. Works perfectly now!

**Comment by sebromero** [comment]
I suggest to bump the pod version to 0.3.1. Do you agree?

**Comment by mikeabdullah** [comment]
There should already be a new pod available as version 0.3.2

**Comment by sebromero** [comment]
Oh yes, you're right. Thx. I was confused because the podfile in the BSManagedDocument repo doesn't reflect the changes yet.

**Comment by mikeabdullah** [comment]
I should just delete that file. Don't see the point of checking it into the repo to be honest

**Comment by Abizern** [comment]
Your podspec should be part of the repository. IMHO.
- It belongs with the code
- It lets people update the podspec if they make changes
- It lets people make pull requests with changes to your podspec
- Somebody else may wish to take over running the main repo.
- Somebody may want to have  a slightly different podspec in their own fork (I don't know, maybe for a private pod spec)
- There may come a time when you will be able to update to cocoa pods using the command line from your project directory (a la Ruby Gems). In anticipation of that glorious day, you want to keep your podspec with your project.

## Either way - the spec is part of the repo, and should be kept up to date.

Abizer Nasir

**Comment by mikeabdullah** [comment]
I disagree. The canonical spec file lives in the CocoaPods repo itself, so having a second copy elsewhere just seems wasteful. And as so aptly demonstrated here, very easy to forget and let them slip out of sync.

**Comment by Abizern** [comment]
As I said "IMHO".

You might want to put a note in the Readme that the repository is available as a podspec at least. 

Unless you think that information belongs in the canonical Cocoapods repository itself?

:)

**Comment by mikeabdullah** [comment]
Good point; updated now
