### ISSUE TITLE
BSManagedDocument and MagicalRecord

### ISSUE THREAD

**Issue by colasbd** [karelia/BSManagedDocument#20]
Hi @karelia !

My goal is to integrate `NSPersistentDocument` and `MagicalRecord`. I am very interested in your project.

I tried to modify it so that it is automatically connected to the `defaultContext` and `rootContext` of `MagicalRecord`.

If you know `MagicalRecord`, maybe you could tell if there is something wrong in what follows. Actually I get crash when saving. 

I have modified `BSManagedDocument` at three places: 

```
- (id)init
{
    [MagicalRecord cleanUp] ;  // <- here

    self = [super init] ;

    if (self)
    {
        //
    }

    return self ;
}
```

and

```
- (NSManagedObjectContext *)managedObjectContext;
{
    if (!_managedObjectContext)
    {
        if (![NSManagedObjectContext instancesRespondToSelector:@selector(initWithConcurrencyType:)])
        {
            [NSException raise:@"Your SDK is too old"
                        format:@"Need 10.7+ to support concurrency types"] ;
        }
        else
        {
            // Setup the rest of the stack for the context

            NSPersistentStoreCoordinator *coordinator = [[NSPersistentStoreCoordinator alloc] initWithManagedObjectModel:[self managedObjectModel]];

            [NSManagedObjectContext MR_initializeDefaultContextWithCoordinator:coordinator] ;

            _managedObjectContext = [NSManagedObjectContext MR_defaultContext] ;

            [super setUndoManager:[_managedObjectContext undoManager]]; // has to be super as we implement -setUndoManager: to be a no-op
        }
    }

    return _managedObjectContext;
}
```

and

```
- (id)contentsForURL:(NSURL *)url ofType:(NSString *)typeName saveOperation:(NSSaveOperationType)saveOperation error:(NSError **)outError;
{
    NSAssert([NSThread isMainThread], @"Somehow -%@ has been called off of the main thread (operation %u to: %@)", NSStringFromSelector(_cmd), (unsigned)saveOperation, [url path]);

    // Grab additional content that a subclass might provide
    if (outError) *outError = nil;  // unusually for me, be forgiving of subclasses which forget to fill in the error
    id additionalContent = [self additionalContentForURL:url saveOperation:saveOperation error:outError];
    if (!additionalContent)
    {
        if (outError) NSAssert(*outError != nil, @"-additionalContentForURL:saveOperation:error: failed with a nil error");
        return nil;
    }


    // On 10.7+, save the main context, ready for parent to be saved in a moment
//    NSManagedObjectContext *context = self.managedObjectContext;
//    if ([context respondsToSelector:@selector(parentContext)])
//    {
//        if (![context save:outError]) return nil;
//    }
    /*
     SUPPORTING MAGICAL RECORD
     */
    [[NSManagedObjectContext MR_defaultContext] MR_saveToPersistentStoreWithCompletion:nil] ;
...
```

I don't know what's wrong... Can it be that the `NSPersistentStoreCoordinator` has no persistent stores.

Thank you!

**Comment by mikeabdullah** [comment]
Hello, my vague understanding of MagicalRecord is that this is a poor fit. The whole point of the document-based architecture is that there can be multiple documents opened by the user at once. This is incompatible with the notion of there being a default or root context.

Beyond that I have basically no knowledge of MagicalRecord. I imagine your best bet is to find a way to work directly with the contexts that `BSManagedDocument` itself creates and maintains.

**Comment by colasbd** [comment]
I realized that what I want to do is not possible. Indeed, an app with NSDocument will have several CoreData stacks whereas MagicalRecord has only one....

**Comment by colasbd** [comment]
Wow!  We wrote the same thing at the same time!

I will use your class so. What is ksManagedDocument? Shall I use it or the last version? Which advice would you give me? Are you still working on this project? Thanks. I want to use your class for using background threads.

**Comment by mikeabdullah** [comment]
Indeed, we did!

Please use the default branch for the latest code, which is `v0.3.x`. I am still working on this project; we ship it as part of our app Sandvox.
