### ISSUE TITLE
Get a persistentStore connected to a file created by BSManagedDocument

### ISSUE THREAD

**Issue by colasbd** [karelia/BSManagedDocument#21]
Here's my situation.

I create a file `preload` with `BSManagedDocument`.
I put it in the main bundle. I want to access it from any instance of `BSManagedDocument`.

Here's what I do.

1, I get the `URL` and then

```
    [myCoordinator addPersistentStoreWithType:NSSQLiteStoreType//NSBinaryStoreType
                                    configuration:nil
                                              URL:preloadURL
                                          options:nil
                                            error:&error] ;
```

But I get an error "Error Domain=NSCocoaErrorDomain Code=256 "Impossible d’ouvrir le fichier." UserInfo=0x61000006da80 {NSSQLiteErrorDomain=14, NSUnderlyingException=unable to open database file}"

2, So I try to be more intelligent and do

```
    [self addToPersistentStoreCoordinator: myCoordinator
                thePersistentStoreWithURL:preloadURL
                                    error:&error] ;
```

where

```
- (void)addToPersistentStoreCoordinator:(NSPersistentStoreCoordinator *)thePersistentStoreCoordinator
              thePersistentStoreWithURL:(NSURL *)storeURL
                                  error:(NSError **)error
{
    // On 10.8+, the coordinator whinges but doesn't fail if you leave out NSReadOnlyPersistentStoreOption and the file turns out to be read-only. Supplying a value makes it fail with a (not very helpful) error when the store is read-only
    BOOL readonly = ([self.document respondsToSelector:@selector(isInViewingMode)] && [self.document isInViewingMode]);

    NSDictionary *options = @{
                              // For apps linked against 10.9+ and supporting 10.6 still, use the old
                              // style journal. Since the journal lives alongside the persistent store
                              // I figure there's a chance it could be copied from a new Mac to an old one
                              // https://developer.apple.com/library/mac/releasenotes/DataManagement/WhatsNew_CoreData_OSX/index.html
#if MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_9 && MAC_OS_X_VERSION_MIN_REQUIRED <= MAC_OS_X_VERSION_10_6
                              NSSQLitePragmasOption : @{ @"journal_mode" : @"DELETE" },
#endif

                              NSReadOnlyPersistentStoreOption : @(readonly)
                              };


    [thePersistentStoreCoordinator addPersistentStoreWithType:NSSQLiteStoreType
                                                 configuration:nil
                                                           URL:storeURL
                                                       options:options
                                                         error:error];
}
```

but, I get the same error.

3, so finally, I end up by creating a special instance of `BSManagedDocument` just to get the coordinator !!!!!

```
    Document * internalDoc = [[Document alloc] initForInternalUse:YES] ;

    [internalDoc readFromURL:preloadURL
                      ofType:NSSQLiteStoreType
                       error:&error] ;


    myCoordinator = internalDoc.managedObjectContext.persitentStoreCoordinator
```

I think there should be a easier way to access the URLs from `BSManagedDocument`.

What I am missing?

Could you provide a class method `+coordinateStoreForURL:(NSURL*)anURL` or maybe ` `+persistentStoreForURL:(NSURL*)anURL` or something like that?

Thanks!

**Comment by mikeabdullah** [comment]
So you have a file in your app bundle, which you want to have available in Core Data. But what for next? Do you want to try and have a multi-store setup for your documents, where the context references both the document on disk, and this global store?

**Comment by colasbd** [comment]
No, I just want to access this file once (at the launching, and then it's over).

The file has been created by the same application, with the method of `BSManagedDocument`.

I don't understand why 

```
 [myCoordinator addPersistentStoreWithType:NSSQLiteStoreType//NSBinaryStoreType
                                    configuration:nil
                                              URL:preloadURL
                                          options:nil
                                            error:&error] ;
```

raises an error. Note that `myCoordinator` is not the coordinator created by `BSManagedDocument` but another coordinator. The trick I am using so it to creat another instance of `BSManagedDocument` only to get the persistent store. I am only interested in getting a persistent store connected to the file, created in a previous stage by `BSManagedDocument` (with the same model).

Thanks!

**Comment by colasbd** [comment]
Hi.

I find how to do. I don't understand why it is necessary. It seems to be related to the support of packages. I still think you could implement a method `+persistentStoreForURL:(NSURL*)anURL`, to have access to datas created by an other instance of `BSManagedDocument`, or maybe

``` objective-C
+ persistentStoreForURL:(NSURL*)anURL andForModel:(NSManagedObject *)aModel
```

What was needed is:

``` objective-C
    NSString * path = [[NSBundle mainBundle] pathForResource:@"preload"
                                                      ofType:@"mytype"];
    NSURL *preloadURL = [NSURL fileURLWithPath:path];

    /*
     I don't know why (comes from BSManagedDocument)
     but the following is necessary
     */
    preloadURL = [preloadURL URLByAppendingPathComponent:@"StoreContent"];
    preloadURL = [preloadURL URLByAppendingPathComponent:@"persistentStore"];
```

**Comment by mikeabdullah** [comment]
OK, let's back up a bit. One of the major points of `BSManagedDocument` is to provide a package-based document format that matches `UIManagedDocument`.

So are you wanting to include the data into your app in a form which matches `BSManagedDocument`'s layout on disk? Or simply to include a raw store file?

**Comment by colasbd** [comment]
I am interested by this  package-based  functionality, but for now, I don't use it.

Here is what I need 
- I am in an instance of `BSManagedDocument`, with everything normal (store, MOC, etc.)
- I want to access the content of a file previously created by my application (so, by another instance of  `BSManagedDocument`, but without opening the document. I just want to have access to the corresponding `NSPersistentStore` so that I can fetch some data there.

Now, it works (with 

``` objective-C
preloadURL = [preloadURL URLByAppendingPathComponent:@"StoreContent"];
preloadURL = [preloadURL URLByAppendingPathComponent:@"persistentStore"];
```

) but I am just suggesting you to provide methods for other users with similar needs.

Thanks for your help.

**Comment by mikeabdullah** [comment]
Ah, so you're just trying to locate the store of this bundled document? If so, I suggest this:

```
NSURL *preloadURL = [[NSBundle mainBundle] URLForResource:@"preload" withExtension:@"mytype"];
preloadURL = [preloadURL URLByAppendingPathComponent:[MyDocument storeContentName]];
preloadURL = [preloadURL URLByAppendingPathComponent:[MyDocument persistentStoreName]];
```

If you want to do much other work with that store, it seems simplest to me to spin up an instance of `BSManagedDocument` (without displaying it) and access the context etc. through that.

**Comment by colasbd** [comment]
OK, thanks!
