### ISSUE TITLE
Where to perform migrations?

### ISSUE THREAD

**Issue by sebromero** [karelia/BSManagedDocument#26]
Which of the `BSManagedDocument` methods should be overridden in order to perform custom migrations? If I do so in `configurePersistentStoreCoordinatorForURL:ofType:modelConfiguration:storeOptions:error:` the application complains while opening the document that the file has been modified by another application.

**Comment by adib** [comment]
You probably forgot to set NSDocument's notion of the file's date after migration?

Thank you

---

Sasmito Adibowo
http://cutecoder.org

**Comment by sebromero** [comment]
Brilliant! Thank you @adib .
