### ISSUE TITLE
BSManagedDocument doesn't compile as of commit  06d687631cc1ff09939e73b5aa70cfe7b813522a

### ISSUE THREAD

**Issue by Motti-Shneor** [karelia/BSManagedDocument#35]
I'm using Xcode 5.1.1 and MacOS SDK 10.9, Deployment target 10.8 and ARC.

There are 5 "ARC casting rules" errors, lines 1013, 1020 and 1022.

They are related to the way you try to send a block in a contextInfo void \* parameter using Block_copy and Block_release. 

Here's a snippet from the compilation error transcript:

PlanktoMetrix II/planktometrix-ii - GitLab Repository/External/BSManagedDocument/BSManagedDocument.m:1013:41: Implicit conversion of block pointer type 'void (^)(BOOL)' to C pointer type 'void *' requires a bridged cast

PlanktoMetrix II/planktometrix-ii - GitLab Repository/External/BSManagedDocument/BSManagedDocument.m:1020:39: Implicit conversion of C pointer type 'void *' to block pointer type 'void (^)(BOOL)' requires a bridged cast

PlanktoMetrix II/planktometrix-ii - GitLab Repository/External/BSManagedDocument/BSManagedDocument.m:1022:5: Cast of block pointer type 'void (^)(BOOL)' to C pointer type 'const void *' requires a bridged cast

**Comment by mikeabdullah** [comment]
Thanks for spotting this. I've just pushed a fix to the `revert-while-closing` branch.
