### ISSUE TITLE
In Yosemite, BSManagedDocument stopped re-opening last open document after relaunch

### ISSUE THREAD

**Issue by Motti-Shneor** [karelia/BSManagedDocument#37]
My application implementation is naive in the area of document management. I leave most of behavior to defaults. 

In all prior OS's my application will automatically re-open documents that were open when I last quit it --- but not in 10.10.x

Is this a known issue with BSManagedDocument, or should I configure my application differently ?

**Comment by mikeabdullah** [comment]
Hi Motti, this isn't a known issue to me. Can you clarify please:

When you say "stopped", do you mean it was working right under Yosemite, but no longer is? Or does it appear to have always been a problem under 10.10?

Which SDK are you compiling against?

**Comment by Motti-Shneor** [comment]
Sorry. It never worked on Yosemite. I just installed Yosemite on my development Mac and found the problem.

I verified on other macs running Yosemite, but I still need to debug a little to give more information.

נשלח מה-iPad שלי

ב-15 במרץ 2015, בשעה 11:45, Mike Abdullah notifications@github.com כתב/ה:

**Comment by mikeabdullah** [comment]
Sorry this one's been languishing a while. Have you figured out the problem? If not, if you send me an example project, I'll cheerfully take a look.

**Comment by Motti-Shneor** [comment]
Yup. Finally I figured it out. My fault, or rather, Apple's fault. When installing Yosemite over previous system (10.9.5 my case), the "Close windows when quitting an App" setting in the "General" Preferences panel has now been set automatically, without user intervention. That means the app automatically closes all open documents before quit, hence, never re-opens them. Resetting this checkbox relieves the problem, so --- no bug.

**Comment by mikeabdullah** [comment]
Aha, excellent news.
