### ISSUE TITLE
No undo manager is created in macOS Sierra

### ISSUE THREAD

**Issue by evanmiller** [karelia/BSManagedDocument#47]
It appears that the behavior of `[NSManagedObjectContext initWithConcurrencyType:]` has changed in Sierra. No undo manager is created by default, so documents do not have an undo manager when building against the Sierra SDK.

I suggest adding logic to `- (NSManagedObjectContext *)managedObjectContext` to create an undo manager if `self.undoManager` is `nil`.

**Comment by Motti-Shneor** [comment]
I can sure do that (and I did) by modifying BSManagedDocument's lazy managedObjectContext accessor to create and add an undoManager right after MOC is created. 

However - I am wondering if there's a nicer way, without modifying the actual class. The way 'managedObjectContext' accessor is written doesn't leave much for a subclass - as it does lots of internal work after the creation of the context. I could add an undoManager later --- but won't I miss actions? and where is the most appropriate time to do that? 

Maybe BSManagedDocument should have a convenience 
-(BOOL)shouldCreateUndoManager { return NO; }
and add (if needed...) based on that? 

Then, a subclass should just override that to return YES.

Should I prepare a simple pull-request?

**Comment by Motti-Shneor** [comment]
Beyond this, there are those no-op overrides of NSDocument / NSPersistentDocument, that confuse me. Maybe I should override these instead? 

It's simple to glue an undoManager to MOC - but how to do it and keep BSManagedDocument happy?
```
// No-ops, like NSPersistentDocument
- (void)setUndoManager:(NSUndoManager *)undoManager { }
- (void)setHasUndoManager:(BOOL)hasUndoManager { }

// Could also implement -hasUndoManager. The NSPersistentDocument docs just say "Returns YES", which you could construe to mean it's overriden there. But I think what it actually means is that the default value for documents is YES, and we've overridden -setHasUndoManager: to be a no-op, so there's no reasonable way for it to return NO
// Update: Some poking around tells me that NSPersistentDocument does in fact override -hasUndoManager. But what that implementation does, who knows! Perhaps it handles the edge case of the MOC having no undo manager

```

**Comment by evanmiller** [comment]
I have been adding this snippet to my `BSManagedDocument` subclass since the 10.12 days:

```
- (void)setManagedObjectContext:(NSManagedObjectContext *)context;
{
    if (context != nil && context.undoManager == nil) {
        NSUndoManager *undoManager = [[NSUndoManager alloc] init];
        context.undoManager = undoManager;
        [undoManager release];
    }
    [super setManagedObjectContext:context];
}
```

Seems to work!
