### ISSUE TITLE
willPresentError & calling super

### ISSUE THREAD

**Issue by seanm** [karelia/BSManagedDocument#6]
A minor point, but the docs for NSDocument's willPresentError: say "For errors you don't want to customize, call the superclass implementation, passing the original error".

This isn't done by BSManagedDocument....

**Comment by Abizern** [comment]
The default implementation just returns the passed in error, which is what the current subclassed `willPresentError:` returns if it doesn't process it any further.

That said - Mike's not averse to pull requests, so you could implement a suggestion :)

**Comment by seanm** [comment]
Yeah, as I said, a minor point.  But NSDocument is intended for subclassing, so one could imagine BSManagedDocument being anywhere in a chain of subclasses, perhaps someone might change its superclass to something else that also overrides willPresentError:
